export const colleges = [
  {
    rank: 1,
    name: "IIT Madras - Indian Institute of Technology (IITM), Chennai",
    fees: 209550,
    placement: { average: 2100000, highest: 20000000 },
    userReviews: 8.7,
    ranking: { india: 3, world: 131 },
    featured: false,
    location: "Chennai, Tamil Nadu",
    totalReviews: 1200,
    icon: "https://example.com/icons/iit-madras.png",
  },
  {
    rank: 2,
    name: "IIT Bombay - Indian Institute of Technology (IITB), Mumbai",
    fees: 208400,
    placement: { average: 1800000, highest: 22000000 },
    userReviews: 9.0,
    ranking: { india: 2, world: 112 },
    featured: false,
    location: "Mumbai, Maharashtra",
    totalReviews: 1300,
    icon: "https://example.com/icons/iit-bombay.png",
  },
  {
    rank: 3,
    name: "IIT Delhi - Indian Institute of Technology (IITD), New Delhi",
    fees: 210000,
    placement: { average: 1900000, highest: 21000000 },
    userReviews: 9.1,
    ranking: { india: 1, world: 117 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 1100,
    icon: "https://example.com/icons/iit-delhi.png",
  },
  {
    rank: 4,
    name: "BITS Pilani - Birla Institute of Technology and Science, Pilani",
    fees: 350000,
    placement: { average: 1400000, highest: 4000000 },
    userReviews: 9.2,
    ranking: { india: 4, world: 240 },
    featured: true,
    location: "Pilani, Rajasthan",
    totalReviews: 1000,
    icon: "https://example.com/icons/bits-pilani.png",
  },
  {
    rank: 5,
    name: "NIT Trichy - National Institute of Technology, Tiruchirappalli",
    fees: 195000,
    placement: { average: 900000, highest: 3000000 },
    userReviews: 8.5,
    ranking: { india: 6, world: 275 },
    featured: false,
    location: "Tiruchirappalli, Tamil Nadu",
    totalReviews: 800,
    icon: "https://example.com/icons/nit-trichy.png",
  },
  {
    rank: 6,
    name: "NIT Warangal - National Institute of Technology, Warangal",
    fees: 145000,
    placement: { average: 900000, highest: 3000000 },
    userReviews: 8.5,
    ranking: { india: 18, world: 290 },
    featured: false,
    location: "Warangal, Telangana",
    totalReviews: 800,
    icon: "https://example.com/icons/nit-warangal.png",
  },
  {
    rank: 7,
    name: "IIIT Hyderabad - International Institute of Information Technology, Hyderabad",
    fees: 280000,
    placement: { average: 1750000, highest: 3500000 },
    userReviews: 8.9,
    ranking: { india: 13, world: 220 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 950,
    icon: "https://example.com/icons/iiit-hyderabad.png",
  },
  {
    rank: 8,
    name: "Thapar Institute of Engineering and Technology, Patiala",
    fees: 300000,
    placement: { average: 850000, highest: 2700000 },
    userReviews: 8.1,
    ranking: { india: 8, world: 290 },
    featured: true,
    location: "Patiala, Punjab",
    totalReviews: 850,
    icon: "https://example.com/icons/thapar-patiala.png",
  },
  {
    rank: 9,
    name: "Delhi Technological University (DTU), New Delhi",
    fees: 185000,
    placement: { average: 1200000, highest: 2900000 },
    userReviews: 8.8,
    ranking: { india: 9, world: 275 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 1050,
    icon: "https://example.com/icons/dtu.png",
  },
  {
    rank: 10,
    name: "Jamia Millia Islamia, New Delhi",
    fees: 60000,
    placement: { average: 650000, highest: 1800000 },
    userReviews: 8.4,
    ranking: { india: 4, world: 220 },
    featured: false,
    location: "New Delhi, Delhi",
    totalReviews: 950,
    icon: "https://example.com/icons/jamia-millia.png",
  },
  {
    rank: 11,
    name: "Manipal Institute of Technology, Manipal",
    fees: 260000,
    placement: { average: 800000, highest: 3200000 },
    userReviews: 8.3,
    ranking: { india: 10, world: 300 },
    featured: false,
    location: "Manipal, Karnataka",
    totalReviews: 950,
    icon: "https://example.com/icons/manipal-institute.png",
  },
  {
    rank: 12,
    name: "RV College of Engineering, Bangalore",
    fees: 210000,
    placement: { average: 750000, highest: 2000000 },
    userReviews: 8.0,
    ranking: { india: 19, world: 310 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 800,
    icon: "https://example.com/icons/rv-college.png",
  },
  {
    rank: 13,
    name: "University of Hyderabad, Hyderabad",
    fees: 89000,
    placement: { average: 600000, highest: 1800000 },
    userReviews: 8.2,
    ranking: { india: 23, world: 340 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 750,
    icon: "https://example.com/icons/university-of-hyderabad.png",
  },
  {
    rank: 14,
    name: "VIT Vellore - Vellore Institute of Technology, Vellore",
    fees: 198000,
    placement: { average: 900000, highest: 4400000 },
    userReviews: 7.9,
    ranking: { india: 15, world: 400 },
    featured: false,
    location: "Vellore, Tamil Nadu",
    totalReviews: 900,
    icon: "https://example.com/icons/vit-vellore.png",
  },
  {
    rank: 15,
    name: "Lovely Professional University, Jalandhar",
    fees: 175000,
    placement: { average: 550000, highest: 1200000 },
    userReviews: 7.4,
    ranking: { india: 30, world: 800 },
    featured: false,
    location: "Jalandhar, Punjab",
    totalReviews: 650,
    icon: "https://example.com/icons/lovely-professional.png",
  },
  {
    rank: 16,
    name: "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
    fees: 210000,
    placement: { average: 750000, highest: 2000000 },
    userReviews: 8.0,
    ranking: { india: 35, world: 750 },
    featured: false,
    location: "Bhubaneswar, Odisha",
    totalReviews: 720,
    icon: "https://example.com/icons/kiit.png",
  },
  {
    rank: 17,
    name: "Nirma University, Ahmedabad",
    fees: 160000,
    placement: { average: 700000, highest: 1800000 },
    userReviews: 7.8,
    ranking: { india: 34, world: 750 },
    featured: false,
    location: "Ahmedabad, Gujarat",
    totalReviews: 650,
    icon: "https://example.com/icons/nirma-university.png",
  },
  {
    rank: 18,
    name: "Amity University, Noida",
    fees: 220000,
    placement: { average: 600000, highest: 1800000 },
    userReviews: 7.5,
    ranking: { india: 20, world: 650 },
    featured: false,
    location: "Noida, Uttar Pradesh",
    totalReviews: 750,
    icon: "https://example.com/icons/amity-noida.png",
  },
  {
    rank: 19,
    name: "Shiv Nadar University, Greater Noida",
    fees: 250000,
    placement: { average: 700000, highest: 2000000 },
    userReviews: 8.1,
    ranking: { india: 40, world: 700 },
    featured: false,
    location: "Greater Noida, Uttar Pradesh",
    totalReviews: 650,
    icon: "https://example.com/icons/shiv-nadar-university.png",
  },
  {
    rank: 20,
    name: "SRM Institute of Science and Technology, Chennai",
    fees: 200000,
    placement: { average: 600000, highest: 1800000 },
    userReviews: 7.6,
    ranking: { india: 32, world: 700 },
    featured: false,
    location: "Chennai, Tamil Nadu",
    totalReviews: 670,
    icon: "https://example.com/icons/srm-chennai.png",
  },
  {
    rank: 21,
    name: "Jadavpur University, Kolkata",
    fees: 60000,
    placement: { average: 600000, highest: 1900000 },
    userReviews: 8.1,
    ranking: { india: 31, world: 500 },
    featured: false,
    location: "Kolkata, West Bengal",
    totalReviews: 900,
    icon: "https://example.com/icons/jadavpur-university.png",
  },
  {
    rank: 22,
    name: "Osmania University, Hyderabad",
    fees: 12000,
    placement: { average: 500000, highest: 1600000 },
    userReviews: 7.4,
    ranking: { india: 33, world: 800 },
    featured: false,
    location: "Hyderabad, Telangana",
    totalReviews: 600,
    icon: "https://example.com/icons/osmania-university.png",
  },
  {
    rank: 23,
    name: "PES University, Bangalore",
    fees: 220000,
    placement: { average: 700000, highest: 1800000 },
    userReviews: 8.0,
    ranking: { india: 24, world: 700 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 600,
    icon: "https://example.com/icons/pes-university.png",
  },
  {
    rank: 24,
    name: "Birla Institute of Technology, Mesra",
    fees: 160000,
    placement: { average: 650000, highest: 1600000 },
    userReviews: 8.0,
    ranking: { india: 25, world: 600 },
    featured: false,
    location: "Mesra, Jharkhand",
    totalReviews: 650,
    icon: "https://example.com/icons/bit-mesra.png",
  },
  {
    rank: 25,
    name: "University of Mumbai, Mumbai",
    fees: 20000,
    placement: { average: 550000, highest: 1200000 },
    userReviews: 7.6,
    ranking: { india: 29, world: 900 },
    featured: false,
    location: "Mumbai, Maharashtra",
    totalReviews: 600,
    icon: "https://example.com/icons/university-of-mumbai.png",
  },
  {
    rank: 26,
    name: "Chandigarh University, Gharuan",
    fees: 160000,
    placement: { average: 550000, highest: 1300000 },
    userReviews: 7.5,
    ranking: { india: 27, world: 800 },
    featured: false,
    location: "Gharuan, Punjab",
    totalReviews: 650,
    icon: "https://example.com/icons/chandigarh-university.png",
  },
  {
    rank: 27,
    name: "Jain University, Bangalore",
    fees: 190000,
    placement: { average: 500000, highest: 1500000 },
    userReviews: 7.4,
    ranking: { india: 36, world: 900 },
    featured: false,
    location: "Bangalore, Karnataka",
    totalReviews: 650,
    icon: "https://example.com/icons/jain-university.png",
  },
  {
    rank: 28,
    name: "Shivaji University, Kolhapur",
    fees: 70000,
    placement: { average: 550000, highest: 1200000 },
    userReviews: 7.4,
    ranking: { india: 38, world: 850 },
    featured: false,
    location: "Kolhapur, Maharashtra",
    totalReviews: 600,
    icon: "https://example.com/icons/shivaji-university.png",
  },
  {
    rank: 29,
    name: "National Institute of Technology, Silchar",
    fees: 160000,
    placement: { average: 600000, highest: 1500000 },
    userReviews: 7.7,
    ranking: { india: 39, world: 850 },
    featured: false,
    location: "Silchar, Assam",
    totalReviews: 600,
    icon: "https://example.com/icons/nit-silchar.png",
  },
  {
    rank: 30,
    name: "Sardar Vallabhbhai Patel Institute of Technology, Vasad",
    fees: 150000,
    placement: { average: 580000, highest: 1400000 },
    userReviews: 7.4,
    ranking: { india: 42, world: 800 },
    featured: false,
    location: "Vasad, Gujarat",
    totalReviews: 600,
    icon: "https://example.com/icons/svpit.png",
  },
];
